kind = "mobile"
previewPath = "/"
title = "Cidade Alerta"
version = "1.0.0"
id = "artifacts/cidade-alerta"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22065

[services.development]
run = "pnpm --filter @workspace/cidade-alerta run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/cidade-alerta", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/cidade-alerta", "run", "serve" ]

[services.env]
PORT = "22065"
BASE_PATH = "/"
